# Config https://docs.astral.sh/ruff/configuration/
line-length = 120
indent-width = 4
exclude = ["*.ipynb"]

# Assume Python 3.8
target-version = "py38"

[lint]
ignore = ["E501"]
fixable = ["ALL"]
unfixable = []
select = ["E", "F", "UP", "B", "SIM", "I", "N"]
