"""This file contains prompts for ArchonConvert operations."""

BASE_ARCHON_FUSER_PROMPT = """You have been provided with a set of responses from various open-source models to the latest user
query. Your task is to synthesize these responses into a single, high-quality response. It is crucial
to critically evaluate the information provided in these responses, recognizing that some of it may
be biased or incorrect. Your response should not simply replicate the given answers but should
offer a refined, accurate, and comprehensive reply to the instruction. Ensure your response is
well-structured, coherent, and adheres to the highest standards of accuracy and reliability.

ORIGINAL PROMPT:
<<original-prompt-placeholder>>

Here is the output generated by the model:

OUTPUT:
{original_output}

{finish_instruction}
"""

BASE_ARCHON_CRITIQUE_PROMPT = """You are a helpful assistant. I will provide you with N responses, each indicated by a numerical identifier (e.g.,
[1], [2], etc.). Evaluate the responses based on their relevance to the instruction

ORIGINAL PROMPT:
<<original-prompt-placeholder>>

Here is the output(s) generated by the model(s):

OUTPUT:
{original_output}

Your task is to critique the output based on the following:
{critique_criteria}

Evaluate the N responses above based on their relevance to the instruction. All the responses should be included
and listed using identifiers. For each response, start the critique with the numerical identifier (e.g., [1]) followed. 
At the end of each response’s analysis, include two new lines to separate the critiques. Do
not include any preface or text after the critiques. Do not include any references to previous critiques within a
critique. Start with the analysis for the first response and end with the analysis for the last response. All of the
N responses should be included and evaluated using identifiers.
"""

COT_QA_CRITIQUE_CRITERIA = """1. Does the JSON object adhere to the required format? Highlight any structural issues.
2. Are the values of the output fields accurate based on the provided context? If any fields are incorrect or missing, provide specific examples.
3. Are there any logical errors in reasoning used to derive the output? Provide detailed feedback on potential mistakes.
"""

COT_QA_IMAGE_CRITIQUE_CRITERIA = """1. Does the JSON object adhere to the required format?
2. Are the values of the output fields accurate based on the provided image(s) and/or text?
3. Are there any logical errors in the model's reasoning when extracting information from images and text?
"""

BASE_ARCHON_REFINEMENT_PROMPT = """You are a helpful assistant tasked with refining the output of model(s) based on a critique.
Below is the original user prompt used to generate the output:

ORIGINAL PROMPT:
<<original-prompt-placeholder>>

Here is the original output(s) generated by the model(s):

OUTPUT:
{original_output}

Here is the critique(s) of the output(s):

CRITIQUE:
{critique_output}

Your task is to refine the original output to address the critique. Ensure that:
{refinement_criteria}

{finish_instruction}
"""

COT_QA_ARCHON_REFINEMENT_CRITERIA = """1. The answer adheres to the required JSON format specified in the original prompt.
2. Correctly derives all values for the output fields based on the provided context.
3. Resolves any logical errors identified in the critique.
"""

COT_QA_IMAGE_ARCHON_REFINEMENT_CRITERIA = """1. The answer adheres to the required JSON format specified in the original prompt.
2. Correctly derives all values for the output fields based on the provided image(s) and/or text.
3. Resolves any logical errors identified in the critique.
"""

