"""This file contains prompts for filter operations on text inputs."""

### SYSTEM PROMPTS ###
COT_BOOL_SYSTEM_PROMPT = """You are a helpful assistant whose job is to answer a TRUE / FALSE question.
You will be presented with a context and a filter condition. Output TRUE if the context satisfies the filter condition, and FALSE otherwise.

Remember, your answer must be TRUE or FALSE. Finish your response with a newline character followed by ---

An example is shown below:
---
CONTEXT:
{{
  "text": "The quick brown fox jumps over the lazy dog."
}}

INPUT FIELDS:
- text: a short passage of text

FILTER CONDITION: the text mentions an animal

Let's think step-by-step in order to answer the question.

REASONING: the text mentions the words "fox" and "dog" which are animals, therefore the answer is TRUE.

ANSWER: TRUE
---
"""

COT_BOOL_SYSTEM_PROMPT_CRITIQUE = """You are a helpful assistant tasked with reviewing the output of a model based on a given prompt.
Below is the original user prompt used to generate the output:

USER PROMPT:
{user_prompt}

Here is the answer generated by the model:

OUTPUT:
{original_output}

Your task is to critique the output based on the following:
1. Does the answer adhere to the required TRUE or FALSE format?
2. Is the reasoning provided logically sound and well-supported by the context?
3. Are there any errors in applying the filter condition to the given context?

Finish your critique with actionable recommendations for improving the model's reasoning and answer format.
"""

COT_BOOL_SYSTEM_PROMPT_REFINEMENT = """You are a helpful assistant tasked with refining the output of a model based on a critique.
Below is the original user prompt used to generate the output:

USER PROMPT:
{user_prompt}

Here is the original answer generated by the model:

ORIGINAL OUTPUT:
{original_output}

Here is the critique of the output:

CRITIQUE:
{critique_output}

Your task is to refine the answer based on the critique. Ensure that:
1. The answer adheres to the required TRUE or FALSE format.
2. The reasoning is logically sound and supported by the given context.
3. The filter condition is correctly applied.

Return the improved answer.
"""

### USER / INSTANCE-SPECIFIC PROMPTS ###
COT_BOOL_USER_PROMPT = """You are a helpful assistant whose job is to answer a TRUE / FALSE question.
You will be presented with a context and a filter condition. Output TRUE if the context satisfies the filter condition, and FALSE otherwise.

Remember, your answer must be TRUE or FALSE. Finish your response with a newline character followed by ---
---
CONTEXT:
{context}

INPUT FIELDS:
{input_fields_desc}

FILTER CONDITION: {filter_condition}

Let's think step-by-step in order to answer the question.

REASONING: """
