import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/quickstart',
        'getting-started/next-steps',
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'user-guide/overview',
        'user-guide/dataset',
        'user-guide/operators',
        'user-guide/optimization',
      ],
    },
    {
      type: 'category',
      label: 'Documentation',
      items: [
        'api/overview',
        {
          type: 'category',
          label: 'Data',
          items: [
            'api/data/dataset',
            'api/data/datarecord',
            'api/data/datarecordcollection',
            'api/data/context',
            'api/data/iter-dataset',
          ],
        },
        {
          type: 'category',
          label: 'Operators',
          items: [
            'api/operators/aggregate',
            {
              type: 'category',
              label: 'Filters',
              items: [
                'api/operators/filter/filter',
                'api/operators/filter/llm-filter',
                'api/operators/filter/non-llm-filter',
              ],
            },
            // {
            //   type: 'category',
            //   label: 'Joins',
            //   items: [
            //     'api/operators/join/join',
            //     'api/operators/join/nested-loops-join',
            //     'api/operators/join/embedding-join',
            //   ],
            // },
            'api/operators/limit',
            'api/operators/logical',
            {
              type: 'category',
              label: 'Maps',
              items: [
                'api/operators/convert/convert',
                'api/operators/convert/critique-and-refine-convert',
                'api/operators/convert/llm-convert',
                'api/operators/convert/mixture-of-agents-convert',
                'api/operators/convert/non-llm-convert',
                'api/operators/convert/rag-convert',
              ],
            },
            'api/operators/physical',
            'api/operators/retrieve',
            'api/operators/scan',
          ],
        },
      ],
    }
  ],
};

export default sidebars;
