site_name: Palimpzest
site_url: https://palimpzest.org
repo_url: https://github.com/mitdbg/palimpzest
repo_name: mitdbg/palimpzest

nav:
  - Home: index.md
  - Introduction:
    - Installation: intro/installation.md
    - Getting Started: intro/getting-started.md
    - Next Steps: intro/next-steps.md
  - User Guide:
    - User Guide Overview: user-guide/overview.md
    - How to Read Your Own Data: user-guide/datareaders.md
    - PZ Operator Overview: user-guide/operators.md
    - Getting Started with Optimization: user-guide/optimization.md
  - Documentation:
    - DataReader: api/datareader.md
    - Dataset: api/dataset.md
    - Operators:
      - Aggregate: api/operators/aggregate.md
      - Convert: api/operators/convert.md
      - Filter: api/operators/filter.md
      - Limit: api/operators/limit.md
      - Retrieve: api/operators/retrieve.md
      - Scan: api/operators/scan.md
    - Optimizer: api/optimizer.md
  - Contact: contact.md

theme:
  name: material
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  # logo: logos/palimpzest-cropped.png
  logo: https://palimpzest-workloads.s3.us-east-1.amazonaws.com/palimpzest-cropped.png
  icon:
    logo: fontawesome/solid/w
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: lime

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: black

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

copyright: Copyright &copy; 2025 MIT Data Systems Group
